"""add_nullable

Revision ID: 6d8d109b3785
Revises: c1bed59d9ac9
Create Date: 2024-06-04 01:25:45.371403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d8d109b3785"
down_revision: Union[str, None] = "c1bed59d9ac9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "phone", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "phone", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
