"""update_user

Revision ID: b761e96727f9
Revises: fe537fa5c772
Create Date: 2024-06-23 10:49:46.351034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b761e96727f9"
down_revision: Union[str, None] = "fe537fa5c772"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "firstname", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "middlename", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "lastname", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "preference", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint("user_phone_key", "user", type_="unique")
    op.drop_constraint("user_preference_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_preference_key", "user", ["preference"])
    op.create_unique_constraint("user_phone_key", "user", ["phone"])
    op.alter_column("user", "preference", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "lastname", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "middlename", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "firstname", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
