"""null_for_success_image

Revision ID: fe537fa5c772
Revises: 6d8d109b3785
Create Date: 2024-06-07 03:00:16.681016

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe537fa5c772"
down_revision: Union[str, None] = "6d8d109b3785"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("image", "is_successful", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "image", "is_successful", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
